const express = require('express')
const router = express.Router()
const {criar, login, mudar, logout, pesquisa} = require('../controllers/user')
const {auth} = require('../auth')
router.post('/signup', criar)
router.post('/login', login)
router.patch('/config/:config', auth, mudar)
router.post('/logout', auth, logout)
router.post('/pesquisa', auth, pesquisa)
module.exports = router